site: creeper.fr
url: https://creeper.fr
title: creeper.fr
description: Le site de Creeper
locale: fr_FR
permalink: pretty
baseurl: ""
disable_disk_cache: true
highlighter: none
author:
  name: "Tristan BRINGUIER"
  url: "https://creeper.fr/"
image: "/assets/img/groot.jpg"
logo: "/assets/img/groot.jpg"
exclude:
  - .jekyll-cache
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
sass:
  sass_dir:          _sass
  style:            :compressed
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap  
  - jekyll-og-image
collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
og_image:
  output_dir: "assets/img"
  domain: "creeper.fr"
  header:
    font_family: "Roboto, Bold"
  image: "https://avatars.githubusercontent.com/u/39345534"
  force: true
  border_bottom:
    width: 20
    fill:
      - "#4cff99"
      - "#4dd8ff"
      - "#1d5f99"
      - "#091816"
      - "#004840"
      - "#035a00"