site: creeper.fr
url: https://creeper.fr
title: creeper.fr
description: Le site de Creeper
locale: fr_FR
permalink: pretty
baseurl: ""
highlighter: none
author: "Tristan BRINGUIER"
image: "/assets/img/groot.jpg"
logo: "/assets/img/groot.jpg"
keep_files:
  - "assets"
exclude:
  - .jekyll-cache
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
sass:
  sass_dir:          _sass
  style:            :compressed
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap  
  - jekyll-og-image
collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
og_image:
  output_dir: "assets/img"
  domain: "creeper.fr"
  force: true
  verbose: true
  border_bottom:
    width: 20
    fill:
      - "#820C02"
      - "#A91401"
      - "#D51F06"
      - "#DE3F24"
      - "#EDA895"